### ISSUE TITLE
Relative paths in IPLD

### ISSUE THREAD

**Issue by nicola** [ipfs/specs#112]
Originally in [interplanetary paths](https://github.com/nicola/cross-data-paths) I included the possibility of having relative paths.

Here I am proposing to add in the specs (and in the js-ipld implementation), the ability to resolve relative paths.
Having relative paths saves space (`../`, instead of a full hash), helps avoiding splitting things in multiple pieces (`../` instead of creating a new object) and finally, allow circular relationships: **merkle graph**!

```
{
  nicola: { '/': hashNicola },
  david: { '/': hashDavid }
}

{
  name: "Nicola",
  friends: [{'/':'../david' }]
}

{
  name: "David",
  friends: [{'/':'../nicola' }]
}
```

**Comment by nicola** [comment]
cc @stebalien, @mildred, @dignifiedquire, @jbenet

**Comment by mildred** [comment]
This would be really nice, but perhaps not something to have upfront. IPLD is complicated enough as it is.

There is also a problem with relative paths. If you do not have the context (the parent directory) you cannot resolve them. We should not abuse them.

**Comment by nicola** [comment]
Moved to new organization, continue the conversation here: https://github.com/ipld/specs/issues/1
