### ISSUE TITLE
Disambiguate the intended interpretation of an /ipns/ target

### ISSUE THREAD

**Issue by Stebalien** [ipfs/specs#114]
Currently, we have `/ipfs` and `/ipns`. Soon, I assume we'll add `/ipld` (`/ipld/HASH/a/b` is will not point to the same object as `/ipfs/HASH/a/b`). So, my question is, what does `/ipns/KEY/a/b` point to? If we say that IPNS links can map to either an IPLD link xor an IPFS link, there's no ambiguity (replace `/ipns/KEY` with the value stored in the DHT, either `/ipfs/HASH` or `/ipld/HASH`). Unfortunately, this doesn't allow one to easily say "I want to talk about this IPFS file at the IPLD level".

My primary motivation is the API/gateway. That is, I need to be able to tell the gateway how to interpret the path I'm handing it. (Really, I'm trying to come up with a design that moves most of the API's functionality to the gateway).

Possible solutions:

1. `/ipns+ipfs/KEY` and `/ipns+ipld/KEY`.
2. `/ipns/KEY` and `/ipns+ipld/KEY` (IPFS is assumed).
3. `/ipns/KEY/ipfs` and `/ipns/KEY/ipld` (multiaddress?).

P.S. Does this problem even make sense or am I missing something?

**Comment by Kubuxu** [comment]
We could solve this problem while setting the IPNS link. You just set the link to full path, not  just a hash.

So you can do: `ipfs name publish /ipfs/Qm...AAA` or `ipfs name publish /ipld/Qm...BBB` and full canonical path will be stored in IPNS record.

I don't know how compatible this is with how current IPNS works but what I can say that solutions with `+` are not the best idea as this means more space used in the `/` which is also supposed to be mounted using FUSE on the system `/`.

**Comment by nicola** [comment]
When publishing an IPNS name, this has a record that contains an a path /ipfs/... or /ipns/.., this should be enough, no?

**Comment by Stebalien** [comment]
I'm working on an alternative API/gateway design and this came up. However, motivating this without explaining the whole API is going to be more trouble than it's worth so I'll just bring this up when I post the API design.
