### ISSUE TITLE
Update Core API Spec

### ISSUE THREAD

**Issue by jlstack** [ipfs/specs#127]
I am currently working on py-ipfs-api and it is difficult to see what the library is missing from the Core API spec. It seems that the specification is not up-to-date and does not reflect the most import elements of the API. Could someone please revise the specifications to better reflect what is actually required of a full implementation?

**Comment by diasdavid** [comment]
@jlstack apologies for taking so long in getting back, you can find the interface for the core-api here: https://github.com/ipfs/interface-ipfs-core
