### ISSUE TITLE
Moving IPLD into its own org

### ISSUE THREAD

**Issue by nicola** [ipfs/specs#128]
Moving to https://github.com/ipld

This consists in:
- [x] moving the spec into `ipld/specs`
- [ ] removing references from `ipfs/specs/ipld` https://github.com/ipfs/specs/pull/129
- [x] moving go-ipld, js-ipld @diasdavid @whyrusleeping 
- [x] update the pointers on npm
- [x] update pointers from `ipld/spec` to `ipfs/specs` and vice-versa

Questions
- Do we need to create ipld/ipld as a welcome page also?
- Do we need to put the specs in `ipld/specs` or just `ipld/ipld`?
- Do we move existing issues?

I am not sure who should take this, maybe @jbenet @lgierth (?)

**Comment by dignifiedquire** [comment]
I can move the spec and js-ipld things. Updating npm will be done after the repos are moved on the next release.
What spec website are you referring to?

**Comment by nicola** [comment]
@dignifiedquire perfect, I just updated the issue for clarity (I just meant the github markdown)

**Comment by dignifiedquire** [comment]
First round is done: 

- https://github.com/ipld/spec
- https://github.com/ipfs/specs/pull/129

**Comment by dignifiedquire** [comment]
Moved

- https://github.com/ipld/js-ipld-cli

**Comment by diasdavid** [comment]
I believe this is all done, closing :)
