### ISSUE TITLE
In the overview document on how to implement IPFS - include links to specs

### ISSUE THREAD

**Issue by pawal** [ipfs/specs#136]
In the [Implement IPFS](https://github.com/ipfs/specs/blob/master/overviews/implement-ipfs.md) overview document, there are links to reference implementations, but no links to the specifications.

**Comment by hsanjuan** [comment]
That document seems pretty outdated itself, any help improving it is welcome.

Might very much delete the whole /overview folder. Apart from outdated, it does not seem that it belongs specifically in a /specs repo.
