### ISSUE TITLE
Is this note still important in the spec?

### ISSUE THREAD

**Issue by kevina** [ipfs/specs#146]
@jbenet (cc @whyrusleeping)

In [repo/fs-repo/README.md](https://github.com/ipfs/specs/blob/93b7bb06aa679f79aae477aad46ca2db0dbfdf51/repo/fs-repo/README.md#blocks-with-an-fs-datastore) (section "blocks/ with an fs-datastore") you have:
```
- the git `idx` and `pack` file could be used to coalesce objects
```

Did this ever apply?  Is it still relevant or important?

Relates to https://github.com/ipfs/go-ipfs/issues/3463

**Comment by whyrusleeping** [comment]
That was just a design though for future implementations. Its not relevant to the current implementation

**Comment by kevina** [comment]
@whyrusleeping so I take it is okay just to replace the text with something accurate?

**Comment by whyrusleeping** [comment]
Yeah, sounds good to me

**Comment by kevina** [comment]
Okay fell free to close this issue.
