### ISSUE TITLE
Outdated IPLD document should be removed or marked as such

### ISSUE THREAD

**Issue by bronger** [ipfs/specs#149]
The first Google hit for “IPFS IPLD” links to https://github.com/ipfs/specs/blob/ipld-spec/merkledag/ipld.md which is outdated and even erroneous in important places.  Please replace this file with a pointer to the current specs (e.g. https://github.com/ipld/specs/tree/master/ipld).

**Comment by lgierth** [comment]
Thanks a lot for bringing this up -- that's indeed horribly outdated.

**Comment by lgierth** [comment]
I've removed that branch - thanks again!
