### ISSUE TITLE
Protect ipfs from claims of enabling piracy?

### ISSUE THREAD

**Issue by roryj78** [ipfs/specs#154]
Hi (first post here so be gentle please!) - I'm reading up on IPFS and it all sounds very exciting groundbreaking, especially when you start getting FileCoin involved. Anyway, I would be interested to know how to intend to protect IPFS from claims that it enables piracy, or digital rights infringement etc?

Obviously I realise a completely decentralised protocol should be hard for authorities to "take down", however surely it would be better if the protocol did not attract this problem from the start? I'm sure the creators will not what themselves pursued by american or international courts, as well as all the bad publicity which will harm the project. When you start also talking about this forming the proof-of-work underwriting a currency, it becomes surely even more important that the legality of the underlying system is not called into question.

So, has any thought be put into this? I wonder if there are some simple steps that could protect the project from this, such as:

1. A statement of intent and disclaimer to be accepted on installation?

2. A system to enable authorities to do a "DRM take down" where authorities could apply for removal, perhaps requiring proof of ownership, and with a small extra admin task to double-check this (all run via the blockchain and perhaps with a small filecoin reward to the nodes who "vote" on this?)

I wonder if these might be enough to protect the project from legal action??

**Comment by lidel** [comment]
Welcome to the community! 

General approach is described in https://github.com/ipfs/faq/issues/36#issuecomment-140567411
In short:  _there will be "denylists"_ explicitly for this purpose, but AFAIK _there are no specs for it yet_.

If you want to get a bigger picture, some interesting discussions related to this topic at `ipfs/faq`:

- https://github.com/ipfs/faq/issues/203: Have I broken the law if I add an mp3 to IPFS and someone discovers its hash and downloads it? 
- https://github.com/ipfs/faq/issues/156: editing/deletion of content and power dynamics
- https://github.com/ipfs/faq/issues/176: How are blocklists maintained?
- https://github.com/ipfs/faq/issues/106:  Legal takedown request compliance
- https://github.com/ipfs/faq/issues/36: Are sting operations possible against IPFS→WWW gates?
- https://github.com/ipfs/faq/issues/9: Can I delete my content from the network?

**Comment by lgierth** [comment]
Thanks @lidel, excellent answer. I'll close this issue here since it's not the right place for general questions about the project. @roryj78 feel free to post follow-up questions in one of the existing issues.
