### ISSUE TITLE
Doube-Slash provide an implementation dependent way of handling a path

### ISSUE THREAD

**Issue by reezer** [ipfs/specs#155]
Since I saw that there is a lot of discussion regarding the ipfs uri scheme, especially using it locally on the FS I wanted to bring up an option that wasn't discussed yet and it probably belongs to ipfs/go-ipfs#1678, but I cannot comment there. 

As can be read up [here](https://jvns.ca/blog/2017/02/08/weird-unix-things-cd/), [POSIX](http://pubs.opengroup.org/onlinepubs/009604599/basedefs/xbd_chap04.html#tag_04_11) allows for a special implementation dependent // behavior. This [has been and is being done](https://unix.stackexchange.com/questions/256497/on-what-systems-is-foo-bar-different-from-foo-bar/256569#256569) in various systems, so it might be an additional option, when using a "local" file system.

(sorry, if this is the wrong place to mention this, or if I overlooked someone already mentioning it)

**Comment by hsanjuan** [comment]
I am not sure this was taken. I'll point you https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md and close this pre-emptively as it is old and was left unanswered.. Re-open if needed.
