### ISSUE TITLE
IPNS DNS TXT resolution caching

### ISSUE THREAD

**Issue by fablabuser** [ipfs/specs#176]
If a given DNS TXT resolution fails, a cached record could be used instead of returning the error `Cound not resolve name.`.

I get error `ipfs resolve -r /ipns/ipfs.io: Could not resolve name.` even though I have already visited /ipns/ipfs.io successfully and recently.

As well as this, nodes could possibly query other nodes for resolution information for a given domain name, if it's local dns-txt-resolutions-cache has no entries, and all other resolution attempts have failed.

**Comment by lidel** [comment]
I think the need for DNS cache was already raised and is tracked in https://github.com/ipfs/go-ipfs/issues/2934
