### ISSUE TITLE
MerkleDAG's might violate SWIRLDS hashgraph patent

### ISSUE THREAD

**Issue by hederahype** [ipfs/specs#187]
The hashgraph consensus algorithm has a patent on a data structure, that is exactly your merkledag with two incoming edges. Please make sure, that you exclude these kinds of hashgraph's from your use cases, due to patent violation! (You can artificially ad a third edge from the "empty vertex", whenever it happens, that a vertex has two incoming edges.)

Thanks,

Marina

**Comment by lgierth** [comment]
Do you mean this one? http://www.swirlds.com/downloads/SWIRLDS-TR-2016-01.pdf

That's from 2016. Where can I read the SWIRLDS patent? Merkle trees go back to the 1970s. 

> The concept of hash trees is named after Ralph Merkle who patented it in 1979.
>
> *-- https://en.wikipedia.org/wiki/Merkle_tree*

**Comment by lgierth** [comment]
@hederahype just to double-check, are you one of the people working on SWIRLDS?

**Comment by Stebalien** [comment]
Those patents are likely invalid under Alice and IPFS predates them by two years.

Other prior art:
  * Git (2005)
  * Bitcoin (2009)
  * Ethereum (2014)

**Comment by hederahype** [comment]
No, I'm not affiliated with SWIRLDS. I thing algorithm patents are absurd for exactly that reason... The patent is linked somewhere on the SWIRLDS homepage. The reason I point this out, is that the hashgraph consensus algorithm uses this structure to reason about gossip communication. 

Then there is another algorithm called PARSEC which is similar to the hashgraph algorithm only in the merkleDAG part. SWIRLDS now thinks this is a rip-off, because they have the patent...

**Comment by whyrusleeping** [comment]
I would love to see swirdls try to enforce that. Especially with all those git commits (merkledag nodes) with two incoming edges (AKA, a merge commit)...

**Comment by MatthiasLohr** [comment]
I have also just stumbled across it and wonder how realistic these patents actually are.

https://www.swirlds.com/ip/
