### ISSUE TITLE
A proposal to include mutability, versioning and ownership of the file as part of the system

### ISSUE THREAD

**Issue by febinkk** [ipfs/specs#190]
**Proposed changes:**
• Instead of the hash of the content, the file will be identified by a random key (file-key) generated at the time of the addition of the file to the system.
• File-key is the public key of a cryptographically generated public/private key pair.
• An integer (version-number) will be generated each time the file is updated by its owner.
• A string (content-string) will be  created by concatenating the hash of the content and version-number of the file.
• Content-string will be signed by the user at each update of the file, using the private key corresponding to the file-key.
• Version-number together with the signed content-string identifies and verifies the ownership of the file, integrity of the content and version of the file.
• Instead of /ipfs/file-hash the user will try to access /ipfs/file-key, the system checks for the latest version of the file and resolves this in to 
/ipfs/file-key/version-number/content-string_signedByPrivateKey
• Alternatively the user can access a particular version of the file with /ipfs/file-key/N, where N is a specific version-number of the file.
• Shortcuts such as /ipfs/file-key/first can be used (to access the earliest available version instead of the latest) when the user doesn't know the exact version-numbet of the file he needs to access. 

**Pros:**
• Each file has an owner.
• Files are mutable, still identifiable with a unique key.
• Only the owner (the one with the private key) can update a file
• All the different versions of a file can be listed by a single key.
• Casual users who do not care about ownership or version can just ignore the private key and version-number, and the system still works the same.

**Cons:**
• Additional burden of verifying the signature, each time, a file is accessed.
• Additional burden of resolving the correct version, while accessing a file.

**Comment by Stebalien** [comment]
You're looking for IPNS. Basically, IPFS gives us immutable files, IPNS gives us mutable (public-key based), versioned pointers to these files.

Checkout the `ipfs name` commands (and the `ipfs key` commands). Unfortunately, *managing* a bunch of keys is not very user-friendly at the moment.

(closing as I believe this has already been implemented, please ask me to reopen if that's not the case)

**Comment by Stebalien** [comment]
See https://docs.ipfs.io/guides/concepts/ipns/

**Comment by ivan386** [comment]
@febinkk You can use ipns in dnslink.
dnslink=/ipns/[your id]
