### ISSUE TITLE
Rebooting the specs repo into a Gitbook

### ISSUE THREAD

**Issue by daviddias** [ipfs/specs#202]
I'm thinking that rebooting the specs repo into a Gitbook and while at it, give a refresh to all of them, would be a great start to get us in a good place when it comes to spec writing, search-ability and maintenance. 

Given that this is a large endeavor, I would like to hear if there are other folks with better suggestions on how maintain specs, writing them and so on. All 👂🏽👂🏽 open :)

**Comment by ianopolous** [comment]
Gitbook seems to be a centralized, proprietary service? I've had great experience using the rust book maker mdbook which outputs static html. 
e.g.
https://doc.rust-lang.org/stable/book/
https://book.peergos.org
It gives you great looking mobile friendly output from markdown input.

Here's the source for how we use it:
https://github.com/peergos/book

**Comment by daviddias** [comment]
The content will always continue to live in a git repo, which we happen to use Github to host. Gitbook would be a UI and a WYSIWYG editor. The gitbook list of features for documentation is quite comprehensive:

- https://docs.gitbook.com/content-editing/releases
- https://docs.gitbook.com/v2-changes/feature-highlights
