### ISSUE TITLE
Move Core API specs to this repo

### ISSUE THREAD

**Issue by daviddias** [ipfs/specs#213]
Hi @alanshaw, what about moving https://github.com/ipfs/interface-js-ipfs-core/tree/master/SPEC to this repo? Using that repo just to contain the core-api tests?

**Comment by alanshaw** [comment]
There's a considerable number of places that link to those docs already. In addition to all the links in the `js-ipfs` and `js-ipfs-http-client` READMEs, there's [error messages in the JS IPFS code base](https://github.com/ipfs/js-ipfs-utils/blob/master/src/files/add-input-validation.js#L27), [links from protoschool](https://github.com/ProtoSchool/protoschool.github.io/pull/254/files#diff-2e8191b8ab5e93196e5cf8f95b041d79R93), links from [js.ipfs.io](https://js.ipfs.io/), the [discuss forums](https://discuss.ipfs.io/search?q=interface-ipfs-core) and probably a whole bunch of links that we don't know about.

**Comment by daviddias** [comment]
Thank you for highlighting that. I take my proposal back.
