### ISSUE TITLE
How should 'validity' schemes be stored?

### ISSUE THREAD

**Issue by daviddias** [ipfs/specs#23]
In IPRS, the validity scheme of a Record is also a MerkleDAG link to an obj, but what should be that obj structure to accept several validity schemes?

@whyrusleeping @jbenet ??

**Comment by jbenet** [comment]
@diasdavid so far i was going to make a few types, and hard code the code for them. can think about self-describing validity code later. a value on the record would define its type (could even be an `@type`), and thus the type of the validity value. with ipld, the validity value no longer _needs to_ be another object always. can be embedded and this saves overhead for small validity values.

**Comment by jbenet** [comment]
lmk if this makes no sense

**Comment by diasdavid** [comment]
Having this in mind: `and hard code the code for them. can think about self-describing validity code later. a value`, makes it easier to understand how to get it done :)
