### ISSUE TITLE
Proposal: remove size property from DAGLinks

### ISSUE THREAD

**Issue by achingbrain** [ipfs/specs#238]
1. They are too easy to fake since they can't be verified unless you fetch the block the link CID refers to, so they are untrustworthy.

2. They include the protobuf encoding overhead so can't be used as cheap file sizes, you have to fetch the block the link CID refers to and unmarshal the UnixFS payload in order to find that out so given point 1, they are redundant[a].

3. We have to jump through lots of hoops in the code to keep the size property around instead of just returning CIDs so are expensive[b].

4. You have to serialize a block to find its size in order to create a DAGLink so they are expensive[c].

5.  You can't create a DAGLink from just a CID without fetching the block it points to in order to get the size so are expensive[d].

I think we should remove the size property from DAGLinks.

cc @Stebalien @alanshaw @ribasushi @mikeal

-----

[a] = Unless you are a protocol spelunker.  Most people are not.  Even if you are, see point 1.
[b] = In terms of code complexity
[c] = In terms of CPU
[d] = In terms of IO

**Comment by mikeal** [comment]
So, I agree with everything in this issue, the only question is when is the best time to take a change like this (which will change the hashes of newly imported files). If this can be included in the upcoming changes for “UnixFS 1.5” then definitely, if not then it might be worth just waiting for UnixFSv2.

**Comment by achingbrain** [comment]
I suppose removing the size field from the protobuf definition will create some really nasty backwards compatibility problems.

The field is optional in the protobuf definition, we could just deprecate it and ignore it going forwards?

In terms of when there's probably a window of the next couple of weeks while the dust settles on the async iterator work.

**Comment by achingbrain** [comment]
I realise I may have opened this issue in the wrong place, it probably belongs on the `ipld/specs` repo so have opened https://github.com/ipld/specs/pull/234

**Comment by mikeal** [comment]
> The field is optional in the protobuf definition, we could just deprecate it and ignore it going forwards?

As you mentioned it’s “easy to fake” and as such should probably be ignored anyway for security purposes.

**Comment by achingbrain** [comment]
Closing this issue because the outcome of ipld/specs#234 is to still generate `Tsize` properties but recommend the user ignores them.
