### ISSUE TITLE
GraceLimit

### ISSUE THREAD

**Issue by Winterhuman** [ipfs/specs#259]
Right now, connections can quickly build up when initially starting an IPFS node (https://github.com/ipfs/go-ipfs/issues/3065, and many other similar issues here). So, I propose introducing a new option called `GraceLimit`.

## GraceLimit

GracePeriod enforces the low and high water levels only when X amount of time has passed. During this time many connection are able to be opened which is most likely the cause of multiple router crashing issues; GracePeriod isn't strict enough. Instead, GraceLimit enforces the low and high water levels using all the same rules as GracePeriod except that instead of time it uses the number of connections.

This is a much stricter means of enforcing connection limits and is much more predictable than GracePeriod, combining it with GracePeriod in case X number of connections are never reached should achieve a more robust and router-friendly system then is currently in place.

**Comment by TheDiscordian** [comment]
This issue was created after some hot debate around router-kill problems mostly referenced here: https://github.com/ipfs/go-ipfs/issues/3320

**Comment by Winterhuman** [comment]
Now that go-libp2p has the ResourceManager, this probably isn't necessary anymore; it essentially provides the same functionality as this, only it uses memory usage instead of number of connections. Closing the issue

**Comment by ShadowJonathan** [comment]
@Winterhuman No, my problem with IPFS is not that it will get too much memory, but that it is opening way too many connections at all times, I want this feature so i can stricly limit my network usage.

Please reopen this issue.

**Comment by markg85** [comment]
I second that opinion @ShadowJonathan 
@Winterhuman, having it in go-libp2p is great but won't solve it for IPFS (kubo). Is there a way to get that option in kubu without rebuilding it and going manual route?

**Comment by aschmahmann** [comment]
> but won't solve it for IPFS (kubo)

So either way this doesn't belong in the specs repo, it's an implementation specific (i.e. kubo in this case) concern.

However, you should be able to set hard connection limits using https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmresourcemgr

**Comment by markg85** [comment]
@aschmahmann I completely forgot about that (so much new stuff these last few months). I'm in the house with the crap-modem tomorrow so I'll be sure to give that a try and see how it works for me. Reporting back in a few days in https://github.com/ipfs/kubo/issues/3320 with my findings.
