### ISSUE TITLE
Record Interface 'Marshal' and 'Unmarshal' is not required anymore

### ISSUE THREAD

**Issue by daviddias** [ipfs/specs#27]
Now that we have marsheling and unmarsheling handled by IPLD implementations (and since a Record is a MerkleDAG Obj that uses IPLD spec), we don't need this anymore on the Record spec:

```
func Marshal(r *Record) ([]byte, error) {
  return recordProtobuf.Marshal(r)
}

func Unmarshal(r *Record, d []byte) (error) {
  return recordProtobuf.Unmarshal(r, d)
}
```

**Comment by jbenet** [comment]
agreed. we should still have a section on serializing, and link to ipld
