### ISSUE TITLE
Clarify HTTP response status codes in reframe/REFRAME_HTTP_TRANSPORT.md for empty results

### ISSUE THREAD

**Issue by BigLep** [ipfs/specs#308]
## Done Criteria
https://github.com/ipfs/specs/blob/main/reframe/REFRAME_HTTP_TRANSPORT.md is clear about the HTTP Status Code to return when a request gets a response with 0 "records".  Is it 200 or 404.

## Why important
For protocol implementers, they need to know what status code to use in this situation since it affects things like metrics.

## Notes
1. I'm opening an issue rather than filing a PR because I won't have the bandwidth to drive this.  We are hitting this ambiguity in the work to have Hydras (reframe client) call storetheindex (reframe server) in https://github.com/libp2p/hydra-booster/issues/162
2. There is good discussion on this topic here: https://softwareengineering.stackexchange.com/questions/203492/when-to-use-http-status-code-404-in-an-api

**Comment by BigLep** [comment]
My vote is that we return a 2xx in this case.  My justification is to be consistent with the montra of "4xx codes Tell a UA it did something wrong, the request it constructed isn't proper and shouldn't try it again, without at least some modification".  In our case, the client hasn't done anything wrong and doesn't need to modify anything.  The reframe server (STI) doesn't have any results at this time.   Yes, it's true that 404 Not Found in Wikipedia has the definition of "The requested resource could not be found but may be available again in the future. Subsequent requests by the client are permissible."  I still think it's cleaner for 4xx response code to be in the territory of "client-side error" rather than special-casing 404 out of this understanding.

**Comment by lidel** [comment]
Agree, if there was no error, but no results, return 200. The only meaning behind HTTP 404 should be that someone forgot to mount `/reframe` on the server.

**Comment by BigLep** [comment]
Other responses in slack (https://filecoinproject.slack.com/archives/C03RQFURZLM/p1660286397948399)

[will scott](https://app.slack.com/team/U014Q0NAA3U)
:exclamation:  [11 hours ago](https://filecoinproject.slack.com/archives/C03RQFURZLM/p1660286689696119?thread_ts=1660286397.948399&cid=C03RQFURZLM)
I’m happy with it being a 200 or similar - i think the main thing is somewhere in either metrics we have associated with delegated routing’s findProvider call, or the combination logic in the hydra, we should have a metric for the number of providers returned.
white_check_mark
eyes
thank-you

[Gus Eggert](https://app.slack.com/team/U0299CQKTCL)
  [3 hours ago](https://filecoinproject.slack.com/archives/C03RQFURZLM/p1660315550621469?thread_ts=1660286397.948399&cid=C03RQFURZLM)
Agree, it's also easier to reason about if we can keep a clean separation between HTTP as merely the RPC transport, and the semantics of the RPC itself (if we can always say "HTTP=200 means the RPC transaction succeed, HTTP!=200 means the RPC transaction failed") (edited)

**Comment by BigLep** [comment]
Ok, so we have agreement on what to do.  Now we just need to add it to the spec.  Any takers?  :)

**Comment by guseggert** [comment]
I clarified this in this commit: https://github.com/ipfs/specs/commit/0b123fa5c3ddf126f55bcec2aa67b2b91247d959
