### ISSUE TITLE
"Other IPFS Overviews" link in README is 404ing 

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/specs#363]
On https://github.com/ipfs/specs#index, under the "IPFS Protocol" bullet point, https://github.com/ipfs/specs/blob/main/overviews is 404ing.

The markdown shows that the link is `[Other IPFS Overviews](/overviews)`. I don't see `/overviews` in the repo, so not sure where this supposed to be linking to.

**Comment by Mr0grog** [comment]
Looks like it was removed in early 2020 with the goal of pushing people to the docs site instead: #243. Someone should either remove the bullet or tweak the text and link to https://docs.ipfs.tech/.
