### ISSUE TITLE
Fix DNSLink at specs.ipfs.tech

### ISSUE THREAD

**Issue by lidel** [ipfs/specs#393]
Figure out why `dig +short ALL _dnslink.specs.ipfs.tech @1.1.1.1` returns no results.

I've checked dnssimple and confirmed  https://github.com/protocol/infra/pull/1140 correctly set it up.
There should be a `CNAME` pointing at `_dnslink.ipfs-specs-website.on.fleek.co`, but DNS does not return it.
Could be a typo, or a hiccup at dnssimple. PErhaps re-apply `CNAME` from https://github.com/protocol/infra/pull/1140?

**Comment by dennis-tra** [comment]
```
$ dig +short ALL _dnslink.specs.ipfs.tech
_dnslink.ipfs-specs-website.on.fleek.co.
```

works for me

**Comment by gmasgras** [comment]
Works here too
```;; ANSWER SECTION:
_dnslink.specs.ipfs.tech. 3600  IN      CNAME   _dnslink.ipfs-specs-website.on.fleek.co.
```

**Comment by lidel** [comment]
yes,  DNS CNAME is there:
```console
$ dig +short ALL _dnslink.specs.ipfs.tech @1.1.1.1
_dnslink.ipfs-specs-website.on.fleek.co.
```


And  TXT record on the target domain:

```console
$ dig +short TXT _dnslink.ipfs-specs-website.on.fleek.co @1.1.1.1
"dnslink=/ipfs/Qmeir9UA5LmqPuNjtBxeHEiZqNfXXpySVv2qX4khVGJwpL
```

But Fleek  fails to recognize it:

> 
![2023-06-02_18-00](https://github.com/ipfs/specs/assets/157609/b2d39d78-622c-401d-8a0e-f009aea283b3)

**Comment by lidel** [comment]
Hm.. we kinda side-step Fleek DNS config. and http://specs.ipfs.tech.ipns.localhost:8080/ loads fine for me now. 
Maybe it was DNS hiccup on my end?

**Comment by lidel** [comment]
Nvm, it seems this got resolved since Mar 30. Probably DNS hiccup that got cached in my local resolver cache.
