### ISSUE TITLE
IPIP: path gateway - range requests clarification (nit)

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/specs#465]
https://github.com/ipfs/specs/blob/937754aa4b7aa96763be40e1503a4fda3f766ad6/src/http-gateways/path-gateway.md?plain=1#L163-L164

Should we be supporting range requests for identity blocks as well? 

ipfs-unixfs-exporter has support for these: https://github.com/search?q=repo%3Aipfs%2Fjs-ipfs-unixfs%20path%3Apackages%2Fipfs-unixfs-exporter%20validateOffsetAndLength&type=code

**Comment by lidel** [comment]
Good question. An inlined block, once "deserialized from identity Multihash" is a valid UnixFS file (it can be `dag-pb` or `raw`), so I think the spec covers them.
