### ISSUE TITLE
http response header for gateways: alt-svc

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/specs#468]
> The [Alt-Svc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc) HTTP header allows a server to indicate that another network location (the "alternative service") can be treated as authoritative for that origin when making future requests.
> 
> Doing so allows new protocol versions to be advertised without affecting in-flight requests, and can also help servers manage traffic. Using an alternative service is not visible to the end user; it does not change the URL or the origin of the request, and does not introduce extra round trips.
> 
> \- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc

can we use this for informing people of multiaddrs or other providers?

**Comment by lidel** [comment]
We already track `alt-svc` in https://github.com/ipfs/in-web-browsers/issues/144, closing as duplicate. 

I think the summary from https://github.com/ipfs/in-web-browsers/issues/144#issuecomment-1030254667 still holds.
