### ISSUE TITLE
Dead links in protocol spec

### ISSUE THREAD

**Issue by bdunlay** [ipfs/specs#66]
Hi all, introducing myself to the state of IPFS through the [protocol spec](https://github.com/ipfs/specs/tree/master/protocol). I've found that there are several dead links in that spec which could use a fix.

A few examples, but not necessarily all:

* networking -> moved to libp2p?
* routing -> moved to libp2p? 
* block exchange?

**Comment by diasdavid** [comment]
Thank you to find those @bdunlay , would you like to submit a PR?

**Comment by bdunlay** [comment]
Sure, would be happy to as best I can.


Sent from Outlook Mobile






On Tue, Jan 26, 2016 at 9:53 AM -0800, "David Dias" <notifications@github.com> wrote:












Thank you to find those @bdunlay , would you like to submit a PR?

**Comment by diasdavid** [comment]
Seems that @mnp handled these :) thank you both!
