### ISSUE TITLE
libp2p Python 3.5+ implementation: some notes

### ISSUE THREAD

**Issue by Mec-iS** [ipfs/specs#68]
Whoever wants to get more familiar with Python3 I/O (as I am actually heavily doing... :+1:  )  can read [here](http://www.slideshare.net/dabeaz/mastering-python-3-io-version-2)
Starting from page 77, it get quite fun! 

Also [this repo](http://nullege.com/codes/show/src@a@c@acidfs-HEAD@setup.py) can be quite interesting starting.

And also considering the differences at [struct](https://docs.python.org/3.5/library/struct.html)

**Comment by diasdavid** [comment]
Hey @Mec-iS, are you familiar with the effort on https://github.com/ipfs/py-ipfs/issues/21? If you want to take part of the development to libp2p in Python, you can start by signing up to the discussion on this issue https://github.com/ipfs/py-ipfs/issues/1 

Closing this issue for now, as this repo is focused on specs and not implementation roadmaps.
