### ISSUE TITLE
Files API spec

### ISSUE THREAD

**Issue by noffle** [ipfs/specs#88]
As far as I've been able to discern, this only exists in the minds of @jbenet @diasdavid @whyrusleeping . Let's get this documented!

**Comment by RichardLitt** [comment]
This should also be added to the go-ipfs mans. 

@noffle What are you proposing that isn't in ipfs-man at the moment?

**Comment by noffle** [comment]
@RichardLitt: here's the current `ipfs files --help` output:

```
    ipfs files - Manipulate unixfs files.

    Files is an API for manipulating IPFS objects as if they were a unix filesystem.
```

We need a document that explains what the Files API is -- its key ideas & abstractions, why it's useful, etc -- in addition to good man/usage documents.

**Comment by RichardLitt** [comment]
Agreed. Thank you.

**Comment by diasdavid** [comment]
@whyrusleeping down to create this spec? :)
