### ISSUE TITLE
Unite the Files API 🗂

### ISSUE THREAD

**Issue by daviddias** [ipfs/specs#98]
> Important note: This is not an entirely new proposal, it has been discussed several times over the course of the last 9 months in different situations with different views and opinions across the IPFS team. This comes to formalize the process so that we can commit and move it forward :)

Several of our users have been mislead to think of IPFS of File System instead of a Graph Database (fair point that is the name of the project after all:D). This mostly comes from the fact that the `cat`, `get` and `add`commands come as first order commands and are the ones mostly used by demos. 

Now, with the addition of the 'Files API', another layer of complexity and indirection was added. The common reaction to it is "Wait, what is Files API, weren't we adding Files all this time?".

With this, we miss the chance to lead our users to understand what a great Graph Database primitives IPFS offers and we also make it really hard for users to understand what Files API is, specially when it has such a generic name.

So, were is the proposal (this is not just me, although I'm the one writing it) that we've discussed through several points in time.

Rename the Files API to `mfs`, this will enable us to have one non generic keyword to call it that we can use with our users and also something that the community will be able to search for or aspect specially, since it has very technical details.

Move the `cat`, `get` and `add` commands to under the files umbrela.

In practical terms, this means:

``` sh
# currently, the file manipulation commands are:
ipfs cat
ipfs get
ipfs add
ipfs files mkdir
ipfs files flush
ipfs files read
ipfs files cp
ipfs files ls
ipfs files stat
ipfs files rm
ipfs files write
```

Next:

``` sh
# Manipulation of files
ipfs files cat
ipfs files get
ipfs files add

# mfs - Mutable File System
ipfs mfs mkdir
ipfs mfs flush
ipfs mfs read
ipfs mfs cp
ipfs mfs ls
ipfs mfs stat
ipfs mfs rm
ipfs mfs write
```

**Comment by dignifiedquire** [comment]
There is also currently `ipfs file ls` which needs to be reviewed in this context

**Comment by dignifiedquire** [comment]
`ipfs get` and `ipfs cat` can be used for custom objects as well, so I'm not sure anymore I am in favor of moving them into the `files` subcategory.

**Comment by Kubuxu** [comment]
Also the names are long established so even if `ipfs get` was to be moved somewhere else backward support should be provided.

This separation is meaningful from interworks perspective but from user perspective it makes almost no sense. I can say that most of my `ipfs` command usage is `ipfs get`, `ipfs cat`, `ipfs add` and `ipfs ls`.

**Comment by noffle** [comment]
This may also be a signal that the `ipfs` command is turning into a grab bag for too many abstractions one could build over basic IPFS blocks (object, files, and mfs).

A slightly more radical idea is to break these out into separate commands altogether, and have `ipfs` be a lightweight core that only manipulates objects (or maybe even just blocks) and we offer other programs to interpret those objects (or blocks) as these various things.

**Comment by whyrusleeping** [comment]
Action items:

- [ ] reference issues from go-ipfs where the decisions for the `ipfs files` commands were made
- [ ] discuss how `ipfs add` can be unified into the files api by making an entry below the files root

**Comment by jbenet** [comment]
links to take into account:
- https://github.com/ipfs/go-ipfs/pull/2233#discussion_r50629405
- https://github.com/ipfs/go-ipfs/pull/1550 (comments, mostly hidden)
- https://github.com/ipfs/go-ipfs/pull/1550#discussion_r37702085
- https://github.com/ipfs/go-ipfs/pull/1769
- https://github.com/ipfs/go-ipfs/pull/1826#issuecomment-149680660
- https://github.com/ipfs/go-ipfs/pull/2039

**Comment by diasdavid** [comment]
@whyrusleeping could you elaborate on the point number two: `discuss how ipfs add can be unified into the files api by making an entry below the files root`, so that everyone can participate in that discussion. Thank you!

**Comment by whyrusleeping** [comment]
What i was thinking was this:

Every call to `ipfs add` should make an entry inside the files api namespace, perhaps at `/added/<DATE>/filename` or `/added/<INDEX>/filename`.  Doing this would accomplish two things:

1. Solve one of our oldest issues: "Where do i see the files i've added?"
2. Make the `ipfs add` more at home as `ipfs files add`

**Comment by Kubuxu** [comment]
Unifying `ipfs add` and `ipfs files add` right now will change hashes returned by the `ipfs add` as `ipfs files add` uses trickledag.

**Comment by diasdavid** [comment]
@Kubuxu could you confirm, AFAIK `ipfs files add` doesn't exist

**Comment by Kubuxu** [comment]
Oh, there isn't `ipfs files add` but `ipfs files write` does that.

**Comment by whyrusleeping** [comment]
@Kubuxu there isnt an issue, `ipfs files add` can continue using the standard chunking scheme and also create entries into the files api namespace. The only caveat is that you wouldnt get the same hash for a file if you used `ipfs files write` to recreate it

**Comment by Kubuxu** [comment]
Or we can wait for 0.5 where hashes change totally either way and not introduce possible confusion.

**Comment by whyrusleeping** [comment]
The hashes will not "change totally" in 0.5. The default object format will change so adding the same content on 0.5 will produce a different hash than adding that content with 0.4. You will still be able to select the old hashing and chunking/encoding format as an option to add and get the same output as before. Also, old hashes will still be accessible and available, all thats happening is a change in defaults.

**Comment by diasdavid** [comment]
Can we have this as one of the discussions for Monday Sprint hangouts? //cc @RichardLitt @em-ly @flyingzumwalt

**Comment by flyingzumwalt** [comment]
I added this to the agenda for the all-hands call.  That's a chance to briefly tell everyone about the issue, make sure everyone knows that the breakout discussion will be happening, and find out who wants to be included in that discussion.

**Comment by jbenet** [comment]
- `ipfs mfs write <thing>` seems way over the top to me, it doesn't pass [the red face test](https://en.wiktionary.org/wiki/red_face_test) trying to tell people like Brewster to use this command.

---

I don't full understand why this is bad:

```
ipfs files cat
ipfs files get
ipfs files add
ipfs files ls
ipfs files mkdir
ipfs files flush
ipfs files read
ipfs files cp
ipfs files stat
ipfs files rm
ipfs files write
```

**Comment by jbenet** [comment]
i know there's "sort of two plumbing things" here, but we're talking about a porcelain command.

- i'm more OK with `ipfs mfs` being a plumbing command, but the command users are told to use and encouraged to use (porcelain) should be way more obvious and understandable to them. `ipfs mfs` is like "wat". `ipfs files` says "hey, use this to store and get files".

**Comment by diasdavid** [comment]
![image](https://cloud.githubusercontent.com/assets/1211152/17837793/a5862e56-67b4-11e6-9f87-917d2aea74a0.png)

I don't necessarily see it as being bad, specially with the addition of adding to mfs the hashes that get added by add, so that it is easy to see what is being stored.

**Comment by jbenet** [comment]
Yeah i think that would solve all our problems, no?

**Comment by kevina** [comment]
Slightly related #2811 as how ever this is solved might solve that issue.

**Comment by diasdavid** [comment]
Just to keep record. Me and @whyrusleeping had a quick chat whole we were together in Lisbon and we agreed that https://github.com/ipfs/specs/issues/98#issuecomment-241261107 is a good way to go next.

**Comment by lidel** [comment]
I believe this discussion continues in https://github.com/ipfs/interface-js-ipfs-core/issues/284
